from datetime import datetime


books = [
    {
        "id": 1,
        "name": "Clean Code",
        "author": "Robert C. Martin",
        "publisher": "Prentice Hall",
        "genre": "Programming",
    },
    {
        "id": 2,
        "name": "The Pragmatic Programmer",
        "author": "Andrew Hunt, David Thomas",
        "publisher": "Addison-Wesley",
        "genre": "Programming",
    },
    {
        "id": 3,
        "name": "Design Patterns: Elements of Reusable Object-Oriented Software",
        "author": "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
        "publisher": "Addison-Wesley",
        "genre": "Software Engineering",
    },
    {
        "id": 4,
        "name": "Python Crash Course",
        "author": "Eric Matthes",
        "publisher": "No Starch Press",
        "genre": "Programming",
    },
    {
        "id": 5,
        "name": "Atomic Habits",
        "author": "James Clear",
        "publisher": "Avery",
        "genre": "Self-Help",
    },
    {
        "id": 6,
        "name": "The Alchemist",
        "author": "Paulo Coelho",
        "publisher": "HarperOne",
        "genre": "Fiction",
    },
    {
        "id": 7,
        "name": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "publisher": "J. B. Lippincott & Co.",
        "genre": "Fiction",
    },
    {
        "id": 8,
        "name": "1984",
        "author": "George Orwell",
        "publisher": "Secker & Warburg",
        "genre": "Fiction",
    },
    {
        "id": 9,
        "name": "The Hobbit",
        "author": "J. R. R. Tolkien",
        "publisher": "George Allen & Unwin",
        "genre": "Fantasy",
    },
    {
        "id": 10,
        "name": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "publisher": "Harper",
        "genre": "History",
    },
]

members = [
    {
        "id": 1,
        "name": "Alice Johnson",
        "joining_date": datetime(2024, 1, 15, 10, 30),
        "exit_date": None,
        "is_active": True,
        "contact": "9876543210",
        "address": "12 Maple Street, Springfield",
    },
    {
        "id": 2,
        "name": "Brian Smith",
        "joining_date": datetime(2023, 8, 10, 9, 15),
        "exit_date": None,
        "is_active": True,
        "contact": "9123456780",
        "address": "45 Oak Avenue, Greenville",
    },
    {
        "id": 3,
        "name": "Catherine Lee",
        "joining_date": datetime(2022, 5, 20, 14, 0),
        "exit_date": datetime(2025, 2, 28, 17, 0),
        "is_active": False,
        "contact": "9988776655",
        "address": "78 Pine Road, Fairview",
    },
    {
        "id": 4,
        "name": "David Wilson",
        "joining_date": datetime(2025, 1, 5, 11, 45),
        "exit_date": None,
        "is_active": True,
        "contact": "9012345678",
        "address": "101 Cedar Lane, Riverside",
    },
    {
        "id": 5,
        "name": "Emma Davis",
        "joining_date": datetime(2023, 11, 12, 16, 20),
        "exit_date": None,
        "is_active": True,
        "contact": "9345678901",
        "address": "56 Birch Drive, Hillcrest",
    },
    {
        "id": 6,
        "name": "Frank Miller",
        "joining_date": datetime(2021, 9, 18, 8, 30),
        "exit_date": datetime(2024, 12, 31, 12, 0),
        "is_active": False,
        "contact": "9765432109",
        "address": "89 Elm Street, Lakeside",
    },
    {
        "id": 7,
        "name": "Grace Anderson",
        "joining_date": datetime(2024, 6, 22, 13, 10),
        "exit_date": None,
        "is_active": True,
        "contact": "9654321098",
        "address": "33 Willow Court, Brookfield",
    },
    {
        "id": 8,
        "name": "Henry Thomas",
        "joining_date": datetime(2023, 3, 8, 10, 0),
        "exit_date": None,
        "is_active": True,
        "contact": "9234567891",
        "address": "17 Cherry Avenue, Kingston",
    },
    {
        "id": 9,
        "name": "Isabella Moore",
        "joining_date": datetime(2022, 10, 30, 15, 45),
        "exit_date": datetime(2025, 1, 15, 9, 30),
        "is_active": False,
        "contact": "9898989898",
        "address": "64 Aspen Way, Oakwood",
    },
    {
        "id": 10,
        "name": "Jack Robinson",
        "joining_date": datetime(2025, 4, 14, 9, 0),
        "exit_date": None,
        "is_active": True,
        "contact": "9556677889",
        "address": "150 Walnut Street, Greenfield",
    },
]

borrowings = [
    {
        "id": 1,
        "book_id": 1,
        "member_id": 1,
        "borrow_date": datetime(2026, 6, 10, 10, 30),
        "due_date": datetime(2026, 6, 24, 10, 30),
        "return_date": datetime(2026, 6, 22, 15, 45),
        "fine": 0,
    },
    {
        "id": 2,
        "book_id": 3,
        "member_id": 2,
        "borrow_date": datetime(2026, 6, 18, 9, 0),
        "due_date": datetime(2026, 7, 2, 9, 0),
        "return_date": None,
        "fine": None,
    },
    {
        "id": 3,
        "book_id": 5,
        "member_id": 4,
        "borrow_date": datetime(2026, 6, 5, 14, 15),
        "due_date": datetime(2026, 6, 19, 14, 15),
        "return_date": datetime(2026, 6, 23, 11, 0),
        "fine": 40,
    },
    {
        "id": 4,
        "book_id": 8,
        "member_id": 7,
        "borrow_date": datetime(2026, 6, 25, 16, 0),
        "due_date": datetime(2026, 7, 9, 16, 0),
        "return_date": None,
        "fine": None,
    },
    {
        "id": 5,
        "book_id": 10,
        "member_id": 10,
        "borrow_date": datetime(2026, 6, 1, 8, 45),
        "due_date": datetime(2026, 6, 15, 8, 45),
        "return_date": datetime(2026, 6, 15, 8, 30),
        "fine": 0,
    },
]
